language: ruby
sudo: false
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
matrix:
  allow_failures:
    - rvm: 2.5
    - rvm: jruby-9.1.15.0
    - rvm: rbx-2
install: bundle install --without=development --jobs=3 --retry=3
