language: ruby
sudo: false
rvm:
  - 1.8
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
matrix:
  allow_failures:
    - rvm: 2.5
    - rvm: jruby-9.1.15.0
    - rvm: rbx-2
install: bundle install --only=test --jobs=3 --retry=3
